service: api

frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x
    profile: serverlessUser
    stage: dev
    region: ap-southeast-1

plugins:
    - serverless-webpack

package:
    individually: true

custom:
    tableName: player-points

functions:
    getUser:
        handler: lambdas/getUser.handler
        events:
            - http:
                  path: get-user/{ID}
                  method: GET
                  cors: true

resources:
    Resources:
        MyDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: ${self:custom.tableName}
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
        