service: api

frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x
    profile: serverlessUser
    stage: dev
    region: ap-southeast-1

package:
    individually: true

functions:
    getUser:
        handler: lambdas/getUser.handler
        events:
            - http:
                  path: get-user/{ID}
                  method: GET
                  cors: true


